// swift-tools-version:5.7
// Package.swift for llama.cpp b8565 (tag b8565, commit b0f0dd3e)
// Supports: iOS 16+, macOS 13+ with Metal GPU acceleration
// Architecture: qwen3vl and all other architectures supported by b8565

import PackageDescription

// ── Source file lists ────────────────────────────────────────────────────────

let llamaSources: [String] = [
    // Core llama
    "src/llama.cpp",
    "src/llama-adapter.cpp",
    "src/llama-arch.cpp",
    "src/llama-batch.cpp",
    "src/llama-chat.cpp",
    "src/llama-context.cpp",
    "src/llama-cparams.cpp",
    "src/llama-grammar.cpp",
    "src/llama-graph.cpp",
    "src/llama-hparams.cpp",
    "src/llama-impl.cpp",
    "src/llama-io.cpp",
    "src/llama-kv-cache.cpp",
    "src/llama-kv-cache-iswa.cpp",
    "src/llama-memory.cpp",
    "src/llama-memory-hybrid.cpp",
    "src/llama-memory-hybrid-iswa.cpp",
    "src/llama-memory-recurrent.cpp",
    "src/llama-mmap.cpp",
    "src/llama-model.cpp",
    "src/llama-model-loader.cpp",
    "src/llama-model-saver.cpp",
    "src/llama-quant.cpp",
    "src/llama-sampler.cpp",
    "src/llama-vocab.cpp",
    "src/unicode.cpp",
    "src/unicode-data.cpp",
    // Model architecture graph builders (src/models/)
    "src/models/afmoe.cpp",
    "src/models/apertus.cpp",
    "src/models/arcee.cpp",
    "src/models/arctic.cpp",
    "src/models/arwkv7.cpp",
    "src/models/baichuan.cpp",
    "src/models/bailingmoe.cpp",
    "src/models/bailingmoe2.cpp",
    "src/models/bert.cpp",
    "src/models/bitnet.cpp",
    "src/models/bloom.cpp",
    "src/models/chameleon.cpp",
    "src/models/chatglm.cpp",
    "src/models/codeshell.cpp",
    "src/models/cogvlm.cpp",
    "src/models/cohere2-iswa.cpp",
    "src/models/command-r.cpp",
    "src/models/dbrx.cpp",
    "src/models/deci.cpp",
    "src/models/deepseek.cpp",
    "src/models/deepseek2.cpp",
    "src/models/delta-net-base.cpp",
    "src/models/dots1.cpp",
    "src/models/dream.cpp",
    "src/models/ernie4-5-moe.cpp",
    "src/models/ernie4-5.cpp",
    "src/models/eurobert.cpp",
    "src/models/exaone-moe.cpp",
    "src/models/exaone.cpp",
    "src/models/exaone4.cpp",
    "src/models/falcon-h1.cpp",
    "src/models/falcon.cpp",
    "src/models/gemma-embedding.cpp",
    "src/models/gemma.cpp",
    "src/models/gemma2-iswa.cpp",
    "src/models/gemma3.cpp",
    "src/models/gemma3n-iswa.cpp",
    "src/models/glm4-moe.cpp",
    "src/models/glm4.cpp",
    "src/models/gpt2.cpp",
    "src/models/gptneox.cpp",
    "src/models/granite-hybrid.cpp",
    "src/models/granite.cpp",
    "src/models/grok.cpp",
    "src/models/grovemoe.cpp",
    "src/models/hunyuan-dense.cpp",
    "src/models/hunyuan-moe.cpp",
    "src/models/internlm2.cpp",
    "src/models/jais.cpp",
    "src/models/jais2.cpp",
    "src/models/jamba.cpp",
    "src/models/kimi-linear.cpp",
    "src/models/lfm2.cpp",
    "src/models/llada-moe.cpp",
    "src/models/llada.cpp",
    "src/models/llama-iswa.cpp",
    "src/models/llama.cpp",
    "src/models/maincoder.cpp",
    "src/models/mamba-base.cpp",
    "src/models/mamba.cpp",
    "src/models/mimo2-iswa.cpp",
    "src/models/minicpm3.cpp",
    "src/models/minimax-m2.cpp",
    "src/models/mistral3.cpp",
    "src/models/modern-bert.cpp",
    "src/models/mpt.cpp",
    "src/models/nemotron-h.cpp",
    "src/models/nemotron.cpp",
    "src/models/neo-bert.cpp",
    "src/models/olmo.cpp",
    "src/models/olmo2.cpp",
    "src/models/olmoe.cpp",
    "src/models/openai-moe-iswa.cpp",
    "src/models/openelm.cpp",
    "src/models/orion.cpp",
    "src/models/paddleocr.cpp",
    "src/models/pangu-embedded.cpp",
    "src/models/phi2.cpp",
    "src/models/phi3.cpp",
    "src/models/plamo.cpp",
    "src/models/plamo2.cpp",
    "src/models/plamo3.cpp",
    "src/models/plm.cpp",
    "src/models/qwen.cpp",
    "src/models/qwen2.cpp",
    "src/models/qwen2moe.cpp",
    "src/models/qwen2vl.cpp",
    "src/models/qwen3.cpp",
    "src/models/qwen35.cpp",
    "src/models/qwen35moe.cpp",
    "src/models/qwen3moe.cpp",
    "src/models/qwen3next.cpp",
    "src/models/qwen3vl-moe.cpp",
    "src/models/qwen3vl.cpp",
    "src/models/refact.cpp",
    "src/models/rnd1.cpp",
    "src/models/rwkv6-base.cpp",
    "src/models/rwkv6.cpp",
    "src/models/rwkv6qwen2.cpp",
    "src/models/rwkv7-base.cpp",
    "src/models/rwkv7.cpp",
    "src/models/seed-oss.cpp",
    "src/models/smallthinker.cpp",
    "src/models/smollm3.cpp",
    "src/models/stablelm.cpp",
    "src/models/starcoder.cpp",
    "src/models/starcoder2.cpp",
    "src/models/step35-iswa.cpp",
    "src/models/t5-dec.cpp",
    "src/models/t5-enc.cpp",
    "src/models/wavtokenizer-dec.cpp",
    "src/models/xverse.cpp",
    // ggml core
    "ggml/src/ggml.c",
    "ggml/src/ggml.cpp",
    "ggml/src/ggml-alloc.c",
    "ggml/src/ggml-backend.cpp",
    "ggml/src/ggml-backend-reg.cpp",
    "ggml/src/ggml-backend-dl.cpp",
    "ggml/src/ggml-opt.cpp",
    "ggml/src/ggml-quants.c",
    "ggml/src/ggml-threading.cpp",
    "ggml/src/gguf.cpp",
    // ggml CPU backend
    "ggml/src/ggml-cpu/ggml-cpu.c",
    "ggml/src/ggml-cpu/ggml-cpu.cpp",
    "ggml/src/ggml-cpu/ops.cpp",
    "ggml/src/ggml-cpu/unary-ops.cpp",
    "ggml/src/ggml-cpu/binary-ops.cpp",
    "ggml/src/ggml-cpu/vec.cpp",
    "ggml/src/ggml-cpu/traits.cpp",
    "ggml/src/ggml-cpu/repack.cpp",
    "ggml/src/ggml-cpu/quants.c",
    "ggml/src/ggml-cpu/hbm.cpp",
    // ggml CPU arch-specific (ARM/NEON for Apple Silicon)
    "ggml/src/ggml-cpu/arch/arm/cpu-feats.cpp",
    "ggml/src/ggml-cpu/arch/arm/quants.c",
    "ggml/src/ggml-cpu/arch/arm/repack.cpp",
]

var sources = llamaSources
var resources: [Resource] = []
var linkerSettings: [LinkerSetting] = []
var cSettings: [CSetting] = [
    .unsafeFlags(["-Wno-shorten-64-to-32", "-O3", "-DNDEBUG"]),
    .unsafeFlags(["-fno-objc-arc"]),
    // Version defines normally injected by CMake
    .define("GGML_VERSION", to: "\"0.9.8\""),
    .define("GGML_COMMIT", to: "\"3d66da180\""),
    // Header search paths so internal #includes resolve correctly
    .headerSearchPath("include"),
    .headerSearchPath("ggml/src"),
    .headerSearchPath("ggml/src/ggml-cpu"),
    .headerSearchPath("src"),
    // CPU backend registration
    .define("GGML_USE_CPU"),
]

#if canImport(Darwin)
// Metal GPU backend (Apple Silicon + all iOS devices)
sources += [
    "ggml/src/ggml-metal/ggml-metal.cpp",
    "ggml/src/ggml-metal/ggml-metal-common.cpp",
    "ggml/src/ggml-metal/ggml-metal-ops.cpp",
    "ggml/src/ggml-metal/ggml-metal-device.cpp",
    "ggml/src/ggml-metal/ggml-metal-device.m",
    "ggml/src/ggml-metal/ggml-metal-context.m",
]
resources.append(.process("ggml/src/ggml-metal/ggml-metal.metal"))
linkerSettings += [
    .linkedFramework("Accelerate"),
    .linkedFramework("Foundation"),
    .linkedFramework("Metal"),
    .linkedFramework("MetalKit"),
    .linkedFramework("MetalPerformanceShaders"),
]
cSettings += [
    .define("GGML_USE_ACCELERATE"),
    .define("GGML_USE_METAL"),
    .headerSearchPath("ggml/src/ggml-metal"),
]
#endif

#if os(Linux)
    cSettings.append(.define("_GNU_SOURCE"))
#endif

let package = Package(
    name: "llama",
    platforms: [
        .macOS(.v13),
        .iOS(.v16),
        .watchOS(.v4),
        .tvOS(.v16)
    ],
    products: [
        .library(name: "llama", targets: ["llama"]),
    ],
    targets: [
        .target(
            name: "llama",
            path: ".",
            exclude: [
                "cmake",
                "examples",
                "scripts",
                "models",
                "tests",
                "docs",
                "ci",
                "benches",
                "common",
                "tools",
                "CMakeLists.txt",
                "CMakePresets.json",
                "build-xcframework.sh",
                "ggml/src/ggml-cuda",
                "ggml/src/ggml-sycl",
                "ggml/src/ggml-vulkan",
                "ggml/src/ggml-opencl",
                "ggml/src/ggml-rpc",
                "ggml/src/ggml-blas",
                "ggml/src/ggml-cann",
                "ggml/src/ggml-hip",
                "ggml/src/ggml-musa",
                "ggml/src/ggml-hexagon",
                "ggml/src/ggml-openvino",
                "ggml/src/ggml-virtgpu",
                "ggml/src/ggml-webgpu",
                "ggml/src/ggml-zdnn",
                "ggml/src/ggml-zendnn",
                "ggml/src/ggml-cpu/amx",
                "ggml/src/ggml-cpu/kleidiai",
                "ggml/src/ggml-cpu/llamafile",
                "ggml/src/ggml-cpu/spacemit",
                "ggml/src/ggml-cpu/arch/loongarch",
                "ggml/src/ggml-cpu/arch/powerpc",
                "ggml/src/ggml-cpu/arch/riscv",
                "ggml/src/ggml-cpu/arch/s390",
                "ggml/src/ggml-cpu/arch/wasm",
                "ggml/src/ggml-cpu/arch/x86",
            ],
            sources: sources,
            resources: resources,
            publicHeadersPath: "include",
            cSettings: cSettings,
            linkerSettings: linkerSettings
        )
    ],
    cxxLanguageStandard: .cxx17
)
